# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jeff Bean
email: jeffreyrobertbean@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal site also containing my blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jeffbean.cool" # the base hostname & protocol for your site
twitter_username: jbean_me
github_username:  jeffbean

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
sass:
    sass_dir: _sass
